apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsclaim2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-client
