apiVersion: v1
kind: LimitRange
metadata:
  name: comprehensive-limits
spec:
  limits:
  - type: Container
    max:
      cpu: "1000m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "100Mi"
    default:
      cpu: "400m"
      memory: "400Mi"
    defaultRequest:
      cpu: "250m"
      memory: "250Mi"
