apiVersion: v1
kind: LimitRange
metadata:
  name: comprehensive-limits
spec:
  limits:
  - type: Container
    max:
      cpu: "1000m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "100Mi"
    defaultRequest:
      cpu: "200m"
      memory: "300Mi"    
