apiVersion: v1
kind: Pod
metadata:
  name: pod-f-injected-limit-fail
  namespace: limitrange-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "700m"   # User Request is 700m
        memory: "600Mi" # User Request is 600Mi
        # Limit is omitted
