apiVersion: v1
kind: Pod
metadata:
  name: pod-e-request-only
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "300m"  # User specifies Request (300m is between min 100m and max 1000m)
        memory: "350Mi" # User specifies Request (350Mi is between min 100Mi and max 1Gi)
