apiVersion: v1
kind: Pod
metadata:
  name: pod-d-limit-only
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "300m" # User sets the Limit
        memory: "350Mi"
