apiVersion: v1
kind: Pod
metadata:
  name: pod-c-min-fail
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "50Mi" # This is < 100Mi (min)
      limits:
        memory: "100Mi"
