apiVersion: v1
kind: Pod
metadata:
  name: preemptor-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "3500m"  # Requesting 3.5 CPU
        memory: "1Gi"
      limits:
        cpu: "3500m"
        memory: "1Gi"
  priorityClassName: high-priority

