apiVersion: v1
kind: Pod
metadata:
  name: sahil2
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

    resources:
     requests:
      memory: "1Gi"
      cpu: "1000m"
     limits:
      memory: "1Gi"
      cpu: "1000m"   

